//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaPoderosaWebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public int Id { get; set; }
        public string NombreProducto { get; set; }
        public string CantidadPorUnidad { get; set; }
        public decimal PrecioUnidad { get; set; }
        public short UnidadEnExistencia { get; set; }
        public byte[] img { get; set; }
        public int ProveedorId { get; set; }
        public int CategoriaId { get; set; }
    
        public virtual Proveedor Proveedor { get; set; }
        public virtual Categoria Categoria { get; set; }
    }
}
